### ISSUE TITLE
View camera image

### ISSUE THREAD

**Issue by CardboardTurkey** [NVIDIA-AI-IOT/trt_pose_hand#10]
Is there anyway to view what the camera sees from within the gesture_classification_live_demo.ipynb notebook?

**Comment by MikyasDesta** [comment]
Yes. Did you try to run the application? It shows both the camera feed and the gesture classes associated with the feed.

**Comment by CardboardTurkey** [comment]
Yeah I tried running the notebook and wasn't able to see a feed. Can you point me to which line exactly is responsible for bringing up the feed?

**Comment by CardboardTurkey** [comment]
Oh is it possible I can't see the feed because I'm running the notebook over ssh?
