### ISSUE TITLE
Weight access

### ISSUE THREAD

**Issue by patripfr** [NVIDIA-AI-IOT/trt_pose_hand#23]
Hi,
downloading the weights apparently is only possible after access is requested. I did so several days ago already. However, nobody seems to confirm. Is this repo still maintained or is anyone still checking the access requests? Otherwise, are there other ways to get the weights?

**Comment by gulati-parth** [comment]
https://github.com/make2explore/Real-Time-Hand-Pose-Estimation-on-Jetson-Nano/blob/main/Pre-Trained%20Models/trt_pose_hand/resnet18_baseline_att_224x224_A_epoch_249.pth

You should be able to download it from here :)

**Comment by patripfr** [comment]
Thanks @gulati-parth !

**Comment by Nicko2102** [comment]
these aren't the same pth files that are listed in the installation directions, is there a way to get  the correct one?

**Comment by fzoric8** [comment]
Hi, 

I'm trying to use this weights, and I get following output: 
``` 
ile "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sequential:
	size mismatch for 1.cmap_conv.weight: copying a param with shape torch.Size([18, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([21, 256, 1, 1]).
	size mismatch for 1.cmap_conv.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([21]).
	size mismatch for 1.paf_conv.weight: copying a param with shape torch.Size([42, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([40, 256, 1, 1]).
	size mismatch for 1.paf_conv.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([40]).
```

So I suspect, those are not correct weights?

EDIT [UPDATE]: Weights for the hand pose estimation are located [here](https://github.com/make2explore/Real-Time-Hand-Pose-Estimation-on-Jetson-Nano/blob/main/Pre-Trained%20Models/trt_pose/hand_pose_resnet18_att_244_244.pth).

**Comment by Nicko2102** [comment]
I'm getting an error "UnpicklingError: invalid load key, '\x0a'." could it be that the file was loaded in a different way, and the unpickling fails because of this?
